apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nichynich01
  template:
    metadata:
      labels:
        app: nichynich01
    spec:
      containers:
        - name: nichynich01
          image: icr.io/nichynich01/personalexpense
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: nichynich01
  type: NodePort
  ports:
    - port: 5000
      nodePort: 30426
